<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="apb" nsURI="http://sesygroup/apb" nsPrefix="apb">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractParticipantBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" lowerBound="1"
        eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceState" lowerBound="1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" lowerBound="1"
        eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendActionTransition" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputMessage" lowerBound="1"
        eType="#//OutputMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveActionTransition" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputMessage" lowerBound="1"
        eType="#//InputMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputMessage" eSuperTypes="#//Message"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputMessage" eSuperTypes="#//Message"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalActionTransition" eSuperTypes="#//Transition"/>
</ecore:EPackage>
